/*
 * Copyright 2026 Abel Ferrer Jiménez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package es.nivel36.janus.service.worksite;

import java.io.Serializable;
import java.time.ZoneId;
import java.util.Collections;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import org.hibernate.annotations.NaturalId;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

import es.nivel36.janus.service.employee.Employee;
import es.nivel36.janus.service.timelog.TimeLog;
import es.nivel36.janus.util.Strings;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

/**
 * JPA entity representing a physical or virtual worksite where employees can
 * register {@link TimeLog} entries.
 *
 * <p>
 * A {@code Worksite} is uniquely identified by its natural identifier
 * ({@code code}) and has a human-readable {@code name}. Each worksite is
 * associated with a {@link ZoneId} that defines the local time zone used when
 * interpreting time-based data.
 * </p>
 *
 * <p>
 * A worksite can be {@link WorksiteScope#GLOBAL global}, which makes it visible
 * to every employee, {@link WorksiteScope#ASSIGNED assigned}, which requires an
 * explicit employee assignment, or {@link WorksiteScope#PERSONAL personal}, in
 * which case it must belong to exactly one owner employee.
 * </p>
 *
 * <p>
 * <strong>Soft delete:</strong> this entity uses logical deletion via the
 * {@code deleted} flag. The Hibernate annotations
 * {@link org.hibernate.annotations.SQLDelete} and
 * {@link org.hibernate.annotations.SQLRestriction} ensure that delete
 * operations update the flag instead of physically removing the row, and that
 * queries exclude logically deleted records by default.
 * </p>
 *
 * <p>
 * Equality and hash code are based solely on the natural identifier
 * ({@code code}), which is assumed to be unique and immutable.
 * </p>
 *
 * @see Employee
 * @see TimeLog
 */
@SQLDelete(sql = "UPDATE WORKSITE SET deleted = true WHERE id = ?")
@SQLRestriction("deleted = false")
@Entity
public class Worksite implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Surrogate primary key of the worksite.
	 *
	 * <p>
	 * This value is auto-generated by the persistence provider and has no business
	 * meaning.
	 * </p>
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * Human-readable name of the worksite.
	 *
	 * <p>
	 * This field is mandatory and must not be {@code null} or empty.
	 * </p>
	 */
	@NotEmpty
	private String name;

	/**
	 * Unique business code of the worksite.
	 *
	 * <p>
	 * Acts as a natural identifier for lookups and external references. This value
	 * is immutable once the entity has been persisted.
	 * </p>
	 */
	@NaturalId
	@NotEmpty
	@Column(updatable = false)
	private String code;

	/**
	 * Time zone associated with the worksite.
	 *
	 * <p>
	 * Determines how local dates and times are interpreted for this worksite. The
	 * value is persisted as a string (for example, {@code "Europe/Madrid"}) using a
	 * JPA {@link jakarta.persistence.Converter}.
	 * </p>
	 */
	@NotNull
	private ZoneId timeZone;

	/**
	 * Visibility scope of the worksite.
	 *
	 * <p>
	 * {@link WorksiteScope#GLOBAL Global} and {@link WorksiteScope#ASSIGNED
	 * Assigned} worksites must not define an owner. {@link WorksiteScope#PERSONAL
	 * Personal} worksites belong to exactly one employee and therefore require
	 * {@link #ownerEmployee} to be populated.
	 * </p>
	 */
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "scope")
	private WorksiteScope scope;

	/**
	 * Logical deletion flag.
	 *
	 * <p>
	 * When {@code true}, the worksite is considered deleted but remains stored in
	 * the database for auditing and historical purposes.
	 * </p>
	 */
	@NotNull
	private boolean deleted = false;

	/**
	 * Employees explicitly associated with this worksite through the legacy
	 * employee-worksite link table.
	 *
	 * <p>
	 * This is the inverse side of the many-to-many relationship defined in
	 * {@link Employee}. The collection is still kept because that association may
	 * continue to serve secondary purposes, even though visibility is now primarily
	 * determined by {@link #scope} and {@link #ownerEmployee}.
	 * </p>
	 */
	@ManyToMany(mappedBy = "worksites")
	private Set<Employee> employees = new HashSet<>();

	/**
	 * Time logs registered at this worksite.
	 *
	 * <p>
	 * This association is lazily loaded. The returned collection must not be
	 * modified directly from outside the entity.
	 * </p>
	 */
	@OneToMany(mappedBy = "worksite", fetch = FetchType.LAZY)
	private Set<TimeLog> timeLogs = new HashSet<>();

	/**
	 * Protected no-argument constructor required by persistence frameworks.
	 *
	 * <p>
	 * This constructor must not be used directly in application code. It exists
	 * solely to allow frameworks such as JPA to instantiate the entity.
	 * </p>
	 */
	Worksite() {
	}

	/**
	 * Creates a new global {@code Worksite} with the given attributes.
	 *
	 * @param code     the unique business code of the worksite; must not be
	 *                 {@code null} or blank
	 * @param name     the human-readable name of the worksite; must not be
	 *                 {@code null} or blank
	 * @param timeZone the time zone associated with the worksite; must not be
	 *                 {@code null}
	 *
	 * @throws NullPointerException     if {@code timeZone} is {@code null}
	 * @throws IllegalArgumentException if {@code code} or {@code name} is blank
	 */
	public Worksite(final String code, final String name, final ZoneId timeZone) {
		this(code, name, timeZone, WorksiteScope.GLOBAL);
	}

	/**
	 * Creates a new {@code Worksite} with the provided scope semantics.
	 *
	 * @param code          the unique business code of the worksite; must not be
	 *                      {@code null} or blank
	 * @param name          the human-readable name of the worksite; must not be
	 *                      {@code null} or blank
	 * @param timeZone      the time zone associated with the worksite; must not be
	 *                      {@code null}
	 * @param scope         the worksite scope; must not be {@code null}
	 * @param ownerEmployee the owner employee for personal worksites; must be
	 *                      {@code null} for global worksites and non-null for
	 *                      personal ones
	 *
	 * @throws NullPointerException     if {@code timeZone} or {@code scope} is
	 *                                  {@code null}, or if {@code ownerEmployee} is
	 *                                  missing for a personal worksite
	 * @throws IllegalArgumentException if {@code code} or {@code name} is blank, or
	 *                                  if a global worksite receives an owner
	 */
	public Worksite(final String code, final String name, final ZoneId timeZone, final WorksiteScope scope) {
		this.code = Strings.requireNonBlank(code, "code can't be null or blank");
		this.name = Strings.requireNonBlank(name, "name can't be null or blank");
		this.timeZone = Objects.requireNonNull(timeZone, "timeZone can't be null");
		this.scope = Objects.requireNonNull(scope, "scope can't be null");
	}

	public Long getId() {
		return this.id;
	}

	/**
	 * Assigns the surrogate identifier of the worksite.
	 *
	 * <p>
	 * This method exists exclusively for testing purposes and must not be used in
	 * production code. It allows controlled assignment of the identifier when
	 * working with manually constructed or detached entities in tests.
	 * </p>
	 *
	 * @param id the identifier to assign
	 */
	void setId(final Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = Strings.requireNonBlank(name, "name can't be null or blank");
	}

	public String getCode() {
		return this.code;
	}

	/**
	 * Returns the time zone associated with the worksite.
	 *
	 * @return the {@link ZoneId} of the worksite
	 */
	public ZoneId getTimeZone() {
		return this.timeZone;
	}

	/**
	 * Updates the time zone of the worksite.
	 *
	 * @param timeZone the new {@link ZoneId}; must not be {@code null}
	 * @throws NullPointerException if {@code timeZone} is {@code null}
	 */
	public void setTimeZone(final ZoneId timeZone) {
		this.timeZone = Objects.requireNonNull(timeZone, "timeZone can't be null");
	}

	/**
	 * Returns the visibility scope of the worksite.
	 *
	 * @return the current {@link WorksiteScope}
	 */
	public WorksiteScope getScope() {
		return this.scope;
	}

	/**
	 * Updates the scope classification of the worksite. The scope can only
	 * increase.
	 *
	 * @param scope the new scope; must not be {@code null}
	 *
	 * @throws NullPointerException     if {@code scope} is {@code null}
	 * @throws IllegalArgumentException if the is decreased
	 */
	public void updateScope(final WorksiteScope scope) {
		Objects.requireNonNull(scope, "scope can't be null");
		if (this.scope == scope) {
			return;
		}
		if (this.scope == WorksiteScope.GLOBAL || scope == WorksiteScope.PERSONAL) {
			throw new IllegalArgumentException("Invalid scope transition from " + this.scope + " to " + scope);
		}
		this.scope = scope;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	/**
	 * Sets the logical deletion flag of this worksite.
	 *
	 * <p>
	 * This method exists exclusively for testing purposes and must not be used in
	 * production code.
	 * </p>
	 *
	 * @param deleted {@code true} to mark the worksite as deleted; {@code false}
	 *                otherwise
	 */
	void setDeleted(final boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * Returns an unmodifiable view of the employees explicitly assigned to this
	 * worksite through the legacy association.
	 *
	 * <p>
	 * The returned collection may be temporarily out of sync if employees are added
	 * to or removed from this worksite after the entity has been loaded and before
	 * this accessor is called.
	 * </p>
	 *
	 * @return an unmodifiable set of {@link Employee} entities
	 */
	public Set<Employee> getEmployees() {
		return Collections.unmodifiableSet(this.employees);
	}

	/**
	 * Replaces the set of explicitly assigned employees.
	 *
	 * <p>
	 * This method exists exclusively for testing purposes and must not be used in
	 * production code.
	 * </p>
	 *
	 * @param employees the set of {@link Employee} entities to assign; must not be
	 *                  {@code null}
	 * @throws NullPointerException if {@code employees} is {@code null}
	 */
	void setEmployees(final Set<Employee> employees) {
		this.employees = Objects.requireNonNull(employees, "employees can't be null");
	}

	/**
	 * Returns an unmodifiable view of the time logs registered at this worksite.
	 *
	 * <p>
	 * The returned collection may be temporarily out of sync if time logs are added
	 * to or removed from this worksite after the entity has been loaded and before
	 * this accessor is called.
	 * </p>
	 *
	 * @return an unmodifiable set of {@link TimeLog} entities
	 */
	public Set<TimeLog> getTimeLogs() {
		return Collections.unmodifiableSet(this.timeLogs);
	}

	/**
	 * Replaces the set of time logs registered at this worksite.
	 *
	 * <p>
	 * This method exists exclusively for testing purposes and must not be used in
	 * production code.
	 * </p>
	 *
	 * @param timeLogs the set of {@link TimeLog} entities to assign; must not be
	 *                 {@code null}
	 * @throws NullPointerException if {@code timeLogs} is {@code null}
	 */
	void setTimeLogs(final Set<TimeLog> timeLogs) {
		this.timeLogs = Objects.requireNonNull(timeLogs, "timeLogs can't be null");
	}
	
	/**
	 * Assigns an employee to the worksite.
	 *
	 * @param employee the {@link Employee} to assign; must not be {@code null}
	 * @return {@code true} if the employee was not already assigned
	 *
	 * @throws NullPointerException if employee is {@code null}
	 */
	public boolean assignEmployee(final Employee employee) {
		Objects.requireNonNull(employee, "employee can't be null");
		return this.employees.add(employee);
	}

	/**
	 * Removes an employee from the worksite.
	 *
	 * @param employee the {@link Employee} to remove; must not be {@code null}
	 * @return {@code true} if the employee is removed
	 *
	 * @throws NullPointerException if employee is {@code null}
	 */
	public boolean removeEmployee(final Employee employee) {
		Objects.requireNonNull(employee, "employee can't be null");
		return this.employees.remove(employee);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.code);
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null || this.getClass() != obj.getClass()) {
			return false;
		}
		final Worksite other = (Worksite) obj;
		return Objects.equals(this.code, other.code);
	}

	@Override
	public String toString() {
		return this.code;
	}
}
