apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janus.grafanaServiceName" . }}
  namespace: {{ include "janus.namespace" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "janus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "janus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          env:
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          ports:
            - containerPort: {{ .Values.grafana.service.port }}
              name: http
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: data
          {{- if .Values.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "janus.grafanaServiceName" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus.grafanaServiceName" . }}
  namespace: {{ include "janus.namespace" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  selector:
    {{- include "janus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
{{- if .Values.grafana.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "janus.grafanaServiceName" . }}-pvc
  namespace: {{ include "janus.namespace" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  {{- end }}
{{- end }}
