apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janus.keycloakServiceName" . }}
  namespace: {{ include "janus.namespace" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      {{- include "janus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak
  template:
    metadata:
      labels:
        {{- include "janus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          args: ["start", "--import-realm"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "janus.fullname" . }}-secrets
                  key: KEYCLOAK_ADMIN
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "janus.fullname" . }}-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ include "janus.postgresKeycloakServiceName" . }}:{{ .Values.postgresKeycloak.service.port }}/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "janus.fullname" . }}-secrets
                  key: KEYCLOAK_DB_PASSWORD
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.hostname | quote }}
            - name: KC_HOSTNAME_STRICT
              value: "false"
          ports:
            - containerPort: {{ .Values.keycloak.service.port }}
              name: http
          volumeMounts:
            - name: realm
              mountPath: /opt/keycloak/data/import/realm-export.json
              subPath: realm-export.json
      volumes:
        - name: realm
          configMap:
            name: {{ include "janus.fullname" . }}-keycloak-realm
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus.keycloakServiceName" . }}
  namespace: {{ include "janus.namespace" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  selector:
    {{- include "janus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
