apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janus.fullname" . }}-secrets
  namespace: {{ include "janus.namespace" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_DB_PASSWORD: {{ .Values.global.appDbPassword | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.global.keycloakDbPassword | quote }}
  KEYCLOAK_ADMIN: {{ .Values.global.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.keycloakAdminPassword | quote }}
