/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationSettingsResponse {
    /**
     * Modification window in days; also controls work shift lookup and precomputation.
     */
    daysUntilLocked: number;
    /**
     * Whether employees can create personal worksites.
     */
    employeeWorksiteCreationAllowed: boolean;
    /**
     * Whether clock-out may use a different worksite from clock-in.
     */
    worksiteChangeDuringShiftAllowed: boolean;
    /**
     * Whether employees can supply explicit time log timestamps.
     */
    employeeManualTimeLogEntryAllowed: boolean;
    /**
     * Stored global zone accepted by Java ZoneId, including UTC and offsets. Surrounding input spaces are trimmed. Does not override worksite or account zones.
     */
    defaultTimezone: string;
}

