/**
 * Janus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationSettingsResponse { 
    daysUntilLocked: number;
    employeeWorkplaceCreationAllowed: boolean;
    worksiteChangeDuringShiftAllowed: boolean;
    employeeManualTimelogEntryAllowed: boolean;
    defaultTimezone: string;
}

