/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationSettingsResponse {
    daysUntilLocked: number;
    /**
     * Canonical name. The obsolete employeeWorkplaceCreationAllowed name is accepted only as a temporary deserialization alias.
     */
    employeeWorksiteCreationAllowed: boolean;
    worksiteChangeDuringShiftAllowed: boolean;
    /**
     * Canonical name. The obsolete employeeManualTimelogEntryAllowed name is accepted only as a temporary deserialization alias.
     */
    employeeManualTimeLogEntryAllowed: boolean;
    defaultTimezone: string;
}

