/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeFormat } from './timeFormat';
import { Theme } from './theme';


export interface AppUserResponse {
    id: string;
    email: string;
    /**
     * Stable employee identifier containing 1 to 50 letters, digits, underscores, or hyphens.
     */
    employeeNumber?: string;
    locale: string;
    timeFormat: TimeFormat;
    theme: Theme;
    defaultTimezone: string;
}


