/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppUserResponse } from './appUserResponse';
import { PageMetadata } from './pageMetadata';


export interface AppUserPage {
    content: Array<AppUserResponse>;
    page: PageMetadata;
}

