/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClockOutWithoutClockInEventResponse {
    employeeEmail: string;
    worksiteCode: string;
    exitTime: string;
    detectedAt: string;
    resolved: boolean;
    invalidated: boolean;
    reason?: string;
    resolvedTimeLogEntry?: string;
    resolvedTimeLogExitTime?: string;
}

