/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClockOutWithoutClockInEventResponse {
    /**
     * Stable employee identifier used by canonical employee routes.
     */
    employeeNumber: string;
    /**
     * Deprecated compatibility field; use employeeNumber instead. It will be removed in a future API version.
     * @deprecated
     */
    employeeEmail: string;
    worksiteCode: string;
    exitTime: string;
    detectedAt: string;
    resolved: boolean;
    invalidated: boolean;
    reason?: string;
    resolvedTimeLogEntry?: string;
    resolvedTimeLogExitTime?: string;
}

