/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorksiteScope } from './worksiteScope';


export interface CreateWorksiteRequest {
    /**
     * Stable worksite code containing 1 to 50 letters, digits, underscores, or hyphens.
     */
    code: string;
    name: string;
    timeZone: string;
    scope: WorksiteScope;
    description?: string | null;
    address?: string | null;
}



