/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleRuleRequest } from './scheduleRuleRequest';


export interface CreateScheduleRequest {
    /**
     * Stable schedule code containing 1 to 50 letters, digits, underscores, or hyphens.
     */
    code: string;
    name: string;
    entryTolerance: string;
    exitTolerance: string;
    rules: Array<ScheduleRuleRequest>;
}

