/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateEmployeeRequest {
    /**
     * Stable employee identifier containing 1 to 50 letters, digits, underscores, or hyphens.
     */
    employeeNumber: string;
    name: string;
    surname: string;
    email: string;
    /**
     * Stable schedule code containing 1 to 50 letters, digits, underscores, or hyphens.
     */
    scheduleCode: string;
}

