/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { EmployeeResponse } from './employeeResponse';


export interface EmployeePage {
    content: Array<EmployeeResponse>;
    page: PageMetadata;
}

