/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleTimeRangeRequest } from './scheduleTimeRangeRequest';


/**
 * effectiveWorkHours must be non-negative and no longer than timeRange.
 */
export interface ScheduleRuleTimeRangeRequest {
    dayOfWeek: ScheduleRuleTimeRangeRequestDayOfWeekEnum;
    effectiveWorkHours: string;
    timeRange: ScheduleTimeRangeRequest;
}
export enum ScheduleRuleTimeRangeRequestDayOfWeekEnum {
    MONDAY = 'MONDAY',
    TUESDAY = 'TUESDAY',
    WEDNESDAY = 'WEDNESDAY',
    THURSDAY = 'THURSDAY',
    FRIDAY = 'FRIDAY',
    SATURDAY = 'SATURDAY',
    SUNDAY = 'SUNDAY'
};



