/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleRuleTimeRangeRequest } from './scheduleRuleTimeRangeRequest';


/**
 * startDate must be on or before endDate when both are supplied.
 */
export interface ScheduleRuleRequest {
    name: string;
    startDate?: string;
    endDate?: string;
    dayOfWeekRanges: Array<ScheduleRuleTimeRangeRequest>;
}

