/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * endTime must be after startTime.
 */
export interface ScheduleTimeRangeRequest {
    startTime: string;
    endTime: string;
}

