/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { ScheduleSummaryResponse } from './scheduleSummaryResponse';


export interface SchedulePage {
    content: Array<ScheduleSummaryResponse>;
    page: PageMetadata;
}

