/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeZoneCatalogItemResponse {
    literal: string;
    level1: string;
    level2?: string | null;
    utc: string;
}

