/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeLogEmployeeResponse {
    /**
     * Stable employee identifier used by canonical employee routes.
     */
    number: string;
    fullName: string;
}

