/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeLogResponse {
    /**
     * Stable employee identifier used by canonical employee routes.
     */
    employeeNumber: string;
    /**
     * Deprecated compatibility field; use employeeNumber instead. It will be removed in a future API version.
     * @deprecated
     */
    employeeEmail: string;
    worksiteCode: string;
    worksiteZoneId: string;
    entryTime: string;
    exitTime?: string | null;
    workTime: { [key: string]: any; } | null;
}

