/**
 * Janus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum TimeFormat {

    H12 = 'H12',

    H24 = 'H24'
}

