/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { TimeZoneCatalogItemResponse } from './timeZoneCatalogItemResponse';


export interface TimeZoneCatalogPage {
    content: Array<TimeZoneCatalogItemResponse>;
    page: PageMetadata;
}

