/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeLogEmployeeResponse } from './timeLogEmployeeResponse';
import { TimeLogWorksiteResponse } from './timeLogWorksiteResponse';


export interface TimeLogResponse {
    employee: TimeLogEmployeeResponse;
    worksite: TimeLogWorksiteResponse;
    entryTime: string;
    exitTime?: string | null;
    workTime: { [key: string]: any; } | null;
}

