/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A RESOLVE action requires entryTime; an INVALIDATE action forbids entryTime.
 */
export interface TransitionClockOutWithoutClockInEventRequest {
    action: TransitionClockOutWithoutClockInEventRequestActionEnum;
    entryTime?: string;
    reason?: string;
}
export enum TransitionClockOutWithoutClockInEventRequestActionEnum {
    RESOLVE = 'RESOLVE',
    INVALIDATE = 'INVALIDATE'
};



