/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateApplicationSettingsRequest {
    daysUntilLocked: number;
    /**
     * Canonical name. During the migration window the API also accepts the obsolete employeeWorkplaceCreationAllowed input name; clients must migrate to this property.
     */
    employeeWorksiteCreationAllowed: boolean;
    worksiteChangeDuringShiftAllowed: boolean;
    /**
     * Canonical name. During the migration window the API also accepts the obsolete employeeManualTimelogEntryAllowed input name; clients must migrate to this property.
     */
    employeeManualTimeLogEntryAllowed: boolean;
    defaultTimezone: string;
}

