/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleRuleRequest } from './scheduleRuleRequest';


export interface UpdateScheduleRequest {
    name: string;
    entryTolerance: string;
    exitTolerance: string;
    rules: Array<ScheduleRuleRequest>;
}

