/**
 * Janus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorksiteStatsResponse {
    worksiteCode: string;
    start: string;
    end: string;
    employeesWhoClockedIn: number;
    erroneousTimeLogs: number;
    totalTimeLogs: number;
    employeesAllowedToClockIn: number;
    distinctSchedulesFromEmployeesWhoClockedIn: number;
}

